newspaper/urls.py
from django.urls import path

from newspaper.views import (
    index,
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    TopicListView,
    TopicDetailView,
    TopicCreateView,
    TopicDeleteView,
)


urlpatterns = [
    path("", index, name="index"),
    path("articles/", ArticleListView.as_view(), name="article-list"),
    path("articles/<int:pk>", ArticleDetailView.as_view(), name="article-detail"),
    path(
        "articles/create/",
        ArticleCreateView.as_view(),
        name="article-create",
    ),
    path(
        "articles/<int:pk>/update/",
        ArticleUpdateView.as_view(),
        name="article-update",
    ),
    path(
        "articles/<int:pk>/delete/",
        ArticleDeleteView.as_view(),
        name="article-delete",
    ),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create",
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/<int:pk>/", TopicDetailView.as_view(), name="topic-detail"),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
]

app_name = "newspaper"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspaper/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        ordering = ["username"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    date_of_publish = models.DateTimeField(auto_now_add=True)
    topic = models.ManyToManyField(Topic, related_name="articles")
    publishers = models.ManyToManyField(Redactor, related_name="articles")

    class Meta:
        ordering = ["-date_of_publish"]

    def __str__(self):
        return f"{self.title}, {self.date_of_publish}"

newspaper/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import MaxValueValidator

from newspaper.models import Article, Topic, Redactor


class ArticleForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    topic = forms.ModelMultipleChoiceField(
        queryset=Topic.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Article
        fields = ["title", "content", "topic", "publishers"]


class RedactorCreateForm(UserCreationForm):
    MAX_EXPERIENCE_VALUE = 55

    years_of_experience = forms.IntegerField(
        required=True,
        validators=[MaxValueValidator(MAX_EXPERIENCE_VALUE)]
    )

    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class RedactorUpdateForm(forms.ModelForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = ("first_name", "last_name", "email")


class ArticleTitleSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=True,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title..."}),
    )

newspaper/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from newspaper.forms import (
    ArticleForm,
    RedactorCreateForm,
    RedactorUpdateForm,
    ArticleTitleSearchForm,
)
from newspaper.models import Redactor, Topic, Article


def index(request):
    """View function for the home page of the site."""

    num_redactors = Redactor.objects.count()
    num_topics = Topic.objects.count()
    num_articles = Article.objects.count()

    context = {
        "num_redactors": num_redactors,
        "num_topics": num_topics,
        "num_articles": num_articles,
    }

    return render(request, "newspaper/index.html", context=context)


class ArticleListView(generic.ListView):
    model = Article
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = ArticleTitleSearchForm(initial={"title": title})
        return context

    def get_queryset(self):
        queryset = Article.objects.prefetch_related("topic", "publishers")
        title = self.request.GET.get("title")

        if title:
            return queryset.filter(title__icontains=title)

        return queryset


class ArticleDetailView(generic.DetailView):
    model = Article


class ArticleCreateView(LoginRequiredMixin, generic.CreateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy("newspaper:article-list")


class ArticleDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Article
    success_url = reverse_lazy("newspaper:article-list")


class ArticleUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Article
    fields = ["title", "content", "topic", "publishers"]

    def get_success_url(self):
        return reverse_lazy(
            "newspaper:article-detail", kwargs={"pk": self.kwargs["pk"]}
        )


class RedactorListView(generic.ListView):
    model = Redactor
    paginate_by = 3


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.prefetch_related(
        "articles__topic",
    )


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreateForm
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorUpdateForm

    def get_success_url(self):
        return reverse_lazy(
            "newspaper:redactor-detail", kwargs={"pk": self.kwargs["pk"]}
        )


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("newspaper:redactor-list")


class TopicListView(generic.ListView):
    model = Topic
    paginate_by = 6


class TopicDetailView(generic.DetailView):
    model = Topic
    queryset = Topic.objects.prefetch_related("articles__publishers")


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newspaper:topic-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>
    Newspaper
  </title>

  <!-- Fontawesome -->
  <link type="text/css" href="{{ ASSETS_ROOT }}/vendor/@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet">
  <!-- Pixel CSS -->
  <link type="text/css" href="{{ ASSETS_ROOT }}/css/pixel.css" rel="stylesheet">

</head>
<body>

{% include 'includes/navigation.html' %}

<main class="main-size">
  {% block content %}{% endblock %}
  {% block pagination %}
    {% include "includes/pagination.html" %}
  {% endblock %}
</main>

{% include 'includes/footer.html' %}

</body>
</html>

templates/includes/footer.html
<footer class="bg-dark text-white footer-custom">

</footer>

templates/includes/navigation.html
<header class="header-global">
  <nav id="navbar-main" aria-label="Primary navigation" class="navbar navbar-expand-lg navbar-theme-primary headroom navbar-dark bg-primary header-custom">
    <div class="container position-relative">
      <div class="navbar-collapse collapse me-auto" id="navbar_global">
        <ul class="navbar-nav navbar-nav-hover align-items-lg-center">
          <li class="nav-item">
            <a href="{% url 'newspaper:index' %}" class="btn btn-outline-gray-100 d-none d-lg-inline me-md-3">
              Home
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'newspaper:redactor-list' %}" class="btn btn-outline-gray-100 d-none d-lg-inline me-md-3">
              Redactors
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'newspaper:article-list' %}" class="btn btn-outline-gray-100 d-none d-lg-inline me-md-3">
              Articles
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'newspaper:topic-list' %}" class="btn btn-outline-gray-100 d-none d-lg-inline me-md-3">
              Topics
            </a>
          </li>
        </ul>
      </div>
      {% if user.is_authenticated %}
        <div class="d-flex align-items-center">
          <span class="btn-outline-gray-100 me-md-3">Logged in as:  {{ user.get_username }}</span>
          <a href="{% url 'logout' %}"
             class="btn btn-outline-gray-100 d-none d-lg-inline me-md-3 ms-3"><span class="fas fa-sign-out-alt me-2"></span> Logout</a>
        </div>
      {% else %}
        <a href="{% url 'login' %}?next={{request.path}}"
           class="btn btn-outline-gray-100 d-none d-lg-inline me-md-3"><span class="fas fa-sign-out-alt me-2"></span> Login</a>
      {% endif %}
    </div>
  </nav>
</header>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination pagination-box">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">Prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">Next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/newspaper/article_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <section class="body-main-centring">
    <h1>Are you sure you want to delete this article?</h1>
    <br>
    <h4>*Warning: you will not be able to restore this article!</h4>
    <br>
    <form action="" method="post">
      {% csrf_token %}
      <br>
      <input type="submit" value="Yes" class="btn btn-danger">
      <a class="btn btn-secondary" href="{% url 'newspaper:article-detail' pk=article.id %}">Cancel</a>
    </form>
  </section>
{% endblock %}

templates/newspaper/article_detail.html
{% extends 'base.html' %}

{% block content %}
  <section class="body-main-centring">
    <h1 class="article-detail-h1">{{ article.title }}</h1>
    <br>
    <p class="article-content">{{ article.content }}</p>
    <p><i>{{ article.date_of_publish }}</i></p>
    <p>
      <strong>Author{{ article.publishers.count|pluralize }}:</strong>
      {% for publisher in article.publishers.all %}
        {{ publisher.first_name }} {{ publisher.last_name }}
      {% endfor %}
    </p>
    {% if user.is_authenticated %}
      <a href="{% url 'newspaper:article-update' pk=article.id %}" class="btn btn-outline-primary">Edit this article</a>
      <a href="{% url 'newspaper:article-delete' pk=article.pk %}" class="btn btn-danger my-xxl-3">Delete this article</a>
    {% endif %}
  </section>
{% endblock %}

templates/newspaper/article_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <section class="body-main-centring">
    <h1>{{ object|yesno:"Update,Create new" }} article</h1>
    <br>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <br>
      <input type="submit" value="Submit" class="btn btn-primary">
      <a class="btn btn-outline-primary" href="{% url 'newspaper:article-list' %}">Cancel</a>
      <br>
    </form>
  </section>
{% endblock %}

templates/newspaper/article_list.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  {% if user.is_authenticated %}
    <div class="container card mb-2 mt-4 create-button">
      <a href="{% url 'newspaper:article-create' %}" class="btn btn-secondary my-xxl-3">Create new article</a>
    </div>
  {% endif %}
  <section class="pt-lg-3 mb-3 pb-lg-2 mt-3 section section-md">
    {% if article_list %}
      <div class="container pt-lg-3 mb-3 pb-lg-2 mt-3">
        <form action="" method="get" class="form-inline" novalidate>
          {{ search_form|crispy }}
          <br>
          <input type="submit" value="Search" class="btn btn-secondary">
        </form>
      </div>
      {% for article in article_list %}
        <div class="container card pt-lg-3 mb-3 pb-lg-2 mt-3">
          <h3>{{ article.title }}</h3>
          <p>Related topics:
            {% for topic in article.topic.all %}
              {{ topic.name }}
              {% if not forloop.last %}, {% endif %}
            {% endfor %}
          </p>
          <p>Created at: {{ article.date_of_publish }}</p>
          <p class="blockquote mb-0">
            Redactors:
            {% for publisher in article.publishers.all %}
              {{ publisher.first_name }} {{ publisher.last_name }}
              {% if not forloop.last %}, {% endif %}
            {% endfor %}
          </p>
          <span><a href="{% url 'newspaper:article-detail' pk=article.id %}" class="btn btn-primary my-xxl-3">Read more</a></span>
        </div>
      {% endfor %}
    {%  else %}
      <h3>There are no articles yet!</h3>
    {% endif %}
  </section>
{% endblock %}

templates/newspaper/index.html
{% extends 'base.html' %}

{% block content %}

  <section class="section-header overflow-hidden pt-lg-5 pb-lg-12 bg-primary text-white">
    <div class="container">
      <div class="row">
        <div class="col-12 text-center">
          <h1 class="fw-bolder display-2">
            Newspaper Agent
          </h1>
          <h2 class="lead fw-normal text-muted mb-4 px-lg-10">
            Best virtual manager to organize your redactors team work
          </h2>
        </div>
      </div>
    </div>
  </section>

  <div class="section py-0">
    <div class="container mt-n10 mt-lg-n12 z-2">
      <div class="row justify-content-center">
        <div class="col-12 col-md-10"><img src="{{ ASSETS_ROOT }}/img/presentation-mockup-new.png"
                                           alt="Pixel Free Mockup"></div>
      </div>
    </div>
  </div>

  <section class="section section-lg">
    <div class="container">
      <div class="row justify-content-center mb-5 mb-lg-6">
        <div class="col-6 col-md-3 text-center mb-4">
          <a href="{% url 'newspaper:topic-list' %}">
            <div class="icon icon-shape icon-lg bg-white shadow-lg border-light rounded-circle mb-4">
              <span class="fas fa-puzzle-piece text-tertiary"></span>
            </div>
            <h3 class="fw-bolder">{{ num_topics }}</h3>
            <h5 class="text-gray">Topics we work on</h5>
          </a>
        </div>
        <div class="col-6 col-md-3 text-center mb-4">
          <a href="{% url 'newspaper:redactor-list' %}">
            <div class="icon icon-shape icon-lg bg-white shadow-lg border-light rounded-circle mb-4">
              <span class="fas fa-pager text-tertiary"></span>
            </div>
            <h3 class="fw-bolder">{{ num_redactors }}</h3>
            <h5 class="text-gray">Redactors in our team</h5>
          </a>
        </div>

        <div class="col-6 col-md-3 text-center">
          <a href="{% url 'newspaper:article-list' %}">
            <div class="icon icon-shape icon-lg bg-white shadow-lg border-light rounded-circle mb-4">
              <span class="fas fa-star text-tertiary "></span>
            </div>
            <h3 class="fw-bolder">{{ num_articles }}</h3>
            <h5 class="text-gray">Articles posted by our redactors</h5>
          </a>
        </div>

      </div>
    </div>
  </section>

{% endblock %}

templates/newspaper/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <section class="body-main-centring">
    <h1>Are you sure you want to delete this redactor?</h1>
    <br>
    <h4>*Warning: you will not be able to restore this profile!</h4>
    <br>
    <form action="" method="post">
      {% csrf_token %}
      <br>
      <input type="submit" value="Yes" class="btn btn-danger">
      <a class="btn btn-secondary" href="{% url 'newspaper:redactor-detail' pk=redactor.pk %}">Cancel</a>
    </form>
  </section>
{% endblock %}

templates/newspaper/redactor_detail.html
{% extends 'base.html' %}

{% block content %}
  <section class="body-main-centring">
    <h1>{{ redactor.first_name }} {{ redactor.last_name }} ({{ redactor.username }})</h1>
    <br>
    <h6>Registered on site: {{ redactor.date_joined }}</h6>
    <h6>Last login: {{ redactor.last_login }}</h6>
    <h6>Years in journalism: {{ redactor.years_of_experience }}</h6>
    <br>
    <h5>E-mail: {{ redactor.email }}</h5>
    <br>
    <h4>Articles:</h4>
    {% for article in redactor.articles.all %}
      <hr>
      <p><strong>Title:</strong> {{ article.title }}</p>
      <p><strong>Date of publish:</strong> {{ article.date_of_publish }}</p>
      <p><strong>Topics:</strong> {% for topic in article.topic.all %}{{ topic.name }} {% endfor %}</p>
    {% empty %}
      <p>This author has not written any articles yet</p>
    {% endfor %}
    <br>
    {% if user.id == redactor.pk %}
      <a href="{% url 'newspaper:redactor-update' pk=redactor.pk %}" class="btn btn-outline-primary">Edit my profile</a>
    {% endif %}
    {% if user.is_staff %}
      <a href="{% url 'newspaper:redactor-delete' pk=redactor.pk %}" class="btn btn-danger">Delete this profile</a>
    {% endif %}
  </section>
{% endblock %}

templates/newspaper/redactor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <section class="body-redactor-centring">
    <h1>{{ object|yesno:"Update,Add new" }} redactor profile</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <br>
      <input type="submit" value="Submit" class="btn btn-primary">
      <a class="btn btn-outline-primary" href="{% url 'newspaper:redactor-list' %}">Cancel</a>
    </form>
  </section>
{% endblock %}

templates/newspaper/redactor_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="section section-sm pb-0 mb-n5">
    <div class="container">
      <div class="row justify-content-center">
        <h3 class="text-center">Our Redactors</h3>
      </div>
    </div>
  </div>

  {% if user.is_staff %}
    <div class="section section-sm pb-0 mb-n5">
      <div class="container">
        <div class="row justify-content-center">
          <a href="{% url 'newspaper:redactor-create' %}" class="btn btn-secondary my-xxl-3">Add new redactor</a>
        </div>
      </div>
    </div>
  {% endif %}


  <!--End of Title section-->
  <div class="section section-md">
    <div class="container">
      <div class="row mb-5">
        {% for redactor in redactor_list %}
          <div class="col-12 col-md-6 col-lg-4 mb-5 mb-md-7 mb-lg-0">
            <div class="card border-0 overflow-hidden">
              <div class="position-relative">
                <img src="{{ ASSETS_ROOT }}/img/team/profile-picture-{{ redactor.pk }}.jpg"
                     onerror="this.onerror=null;this.src='{{ ASSETS_ROOT }}/img/team/default_image.jpg';"
                     class="card-img-top"
                     alt="Portrait">
              </div>
              <div
                  class="card-body position-relative mt-n6 mx-2 bg-white border border-gray-300 text-center rounded">
                <h3 class="h5 card-title">{{ redactor.first_name }} {{ redactor.last_name }}</h3>
                <p class="mt-3">Years in journalism: {{ redactor.years_of_experience }}</p>
                <div class="btn-group">
                  <a href="{% url 'newspaper:redactor-detail' pk=redactor.id %}">
                    <button class="btn btn-secondary btn-icon">
                      <span class="me-1"><span class="far fa-user"></span></span>
                      View profile
                    </button>
                  </a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}

templates/newspaper/topic_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <section class="body-main-centring">
    <h1>Are you sure you want to delete this topic?</h1>
    <br>
    {% if topic.articles.count %}
      <h4>*Warning: this topic relates to {{ topic.articles.count }} article{{ topic.articles.count|pluralize }}!</h4>
    {% endif %}
    <br>
    <form action="" method="post">
      {% csrf_token %}
      <br>
      <input type="submit" value="Yes" class="btn btn-danger">
      <a class="btn btn-secondary" href="{% url 'newspaper:topic-detail' pk=topic.pk %}">Cancel</a>
    </form>
  </section>
{% endblock %}

templates/newspaper/topic_detail.html
{% extends 'base.html' %}

{% block content %}

  <section class="pt-lg-3 mb-3 pb-lg-2 mt-3 section section-md">
    <div class="container pt-lg-3 mb-3 pb-lg-2 mt-3">
      <h1>
        Topic: {{ topic.name }}
        {% if user.is_authenticated %}
          <a href="{% url 'newspaper:topic-delete' pk=topic.pk %}" class="btn btn-danger my-xxl-3 delete-topic">Delete this topic</a>
        {% endif %}
      </h1>
    </div>
    {% if topic.articles.all %}
      {% for article in topic.articles.all %}
        <div class="container card pt-lg-3 mb-3 pb-lg-2 mt-3">
          <h3>{{ article.title }}</h3>
          <br>
          <p>Created at: {{ article.date_of_publish }}</p>
          <p class="blockquote mb-0">
            Redactors:
            {% for publisher in article.publishers.all %}
              {{ publisher.first_name }} {{ publisher.last_name }}
              {% if not forloop.last %}, {% endif %}
            {% endfor %}
          </p>
          <span>
            <a href="{% url 'newspaper:article-detail' pk=article.id %}" class="btn btn-primary my-xxl-3">
              Read more
            </a>
          </span>
        </div>
      {% endfor %}
    {%  else %}
      <div class="container pt-lg-3 mb-3 pb-lg-2 mt-3">
        <h3>There are no articles for this topic yet!</h3>
      </div>
    {% endif %}
  </section>

{% endblock %}

templates/newspaper/topic_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <section class="body-main-centring">
    <h1>Create new topic</h1>
    <br>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <br>
      <input type="submit" value="Submit" class="btn btn-primary">
      <a class="btn btn-outline-primary" href="{% url 'newspaper:topic-list' %}">Cancel</a>
      <br>
    </form>
  </section>
{% endblock %}

templates/newspaper/topic_list.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <!-- Section -->
    <div class="section section-md">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12 col-md-10 col-lg-8">
            <!-- Tab Nav -->
            <div class="nav-wrapper position-relative mb-2">
              {% if user.is_authenticated %}
                <div class="container card mb-2 mt-4 create-button">
                  <a href="{% url 'newspaper:topic-create' %}" class="btn btn-secondary my-xxl-3">Create new topic</a>
                </div>
              {% endif %}
              <ul class="nav nav-pills nav-fill flex-column flex-md-row" id="tabs-text" role="tablist">
                {% for topic in topic_list %}
                  <li class="nav-item topic-item">
                    <a class="nav-link mb-sm-3 mb-md-0" id="tabs-text-2-tab" data-bs-toggle="tab"
                       href="{% url 'newspaper:topic-detail' pk=topic.pk %}" role="tab" aria-controls="tabs-text-2"
                       aria-selected="false"><strong>{{ topic.name }}</strong></a>
                  </li>
                {% endfor %}
              </ul>
            </div>
            <!-- End of Tab Nav -->
          </div>
        </div>
      </div>
    </div>
    <!-- End of Section -->

  </main>
  <section class="pt-lg-3 mb-3 pb-lg-2 mt-3 section section-md">

  </section>
{% endblock %}